name: manage-azure-policy-62cd439b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/policies/Azure_Data_Factory_integration_runtime_should_be_SHIR_d8a56d89-39f8-4fa4-8904-d4e351bc4a09/**'
#      - .github/workflows/manage-azure-policy-62cd439b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_62cd439b}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/policies/Azure_Data_Factory_integration_runtime_should_be_SHIR_d8a56d89-39f8-4fa4-8904-d4e351bc4a09/**
